### ISSUE TITLE
`content_info.attributes` for vector datasets do not appear in 19139 xml docs

### ISSUE THREAD

**Issue by davemfish** [natcap/geometamaker#3]
An MCF section like this:

```
content_info:
  attributes:
  - abstract: ''
    name: ws_id
    title: ''
    type: integer
    units: ''
  - abstract: ''
    name: subws_id
    title: ''
    type: integer
    units: ''
  - abstract: ''
    name: ws_name
    title: ''
    type: string
    units: ''
```

The data does not appear to translate through to an xml doc created using `pygeometa`:
```python
iso_schema = ISO19139OutputSchema()
xml_string = iso_schema.write(self.mcf)
```

Inspecting the jinja2 template (`pygeometa\schemas\iso19139\main.j2`) I find this section,

```xml
  {% if record['content_info'] %}
  <gmd:contentInfo>
    {% if record['content_info']['type'] == 'image' %}
    <gmd:MD_ImageDescription>
      <gmd:attributeDescription>
```
And no other `content_info['type']` besides 'image' seems to be supported by the template. But the core MCF schema allows for:

```yaml
    content_info:
        type: object
        properties:
            type:
                type: string
                description: Content type
                enum:
                    - coverage
                    - image
                    - feature_catalogue
```
I've been using "image" for rasters and "coverage" for vectors.
